name: thinkfeellearn
favicon: null
layout_spectrum: 0.27141
typography_spectrum: 0.49278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#a36100'
    - '#b6ad98'
    - '#004066'
    - '#43722a'
  brandStrength: 0.5
  lightness: 0.25190891278907657
  saturation: 0.9747300997842103
  rhythmicContrast: 0.20213487790897489
purpose: []
