name: Mid-City
favicon: null
layout_spectrum: 0.27141
typography_spectrum: 0.49278
title: A Garden Grows Here
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#5e5955'
    - '#dde2e6'
    - '#919297'
    - '#c46c5d'
  brandStrength: 0.5
  lightness: 0.25190891278907657
  saturation: 0.9747300997842103
  rhythmicContrast: 0.20213487790897489
purpose: []
