name: thinkfeellearn
favicon: null
layout_spectrum: 0.88457
typography_spectrum: 0.49278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#231b18'
    - '#0077c6'
    - '#a9562e'
    - '#70c1f1'
  brandStrength: 0.25
  lightness: 0.25190891278907657
  saturation: 0.9747300997842103
  rhythmicContrast: 0.20213487790897489
purpose: []
