name: thinkfeellearn
favicon: null
layout_spectrum: 0.5310964460950345
typography_spectrum: 0.44588781357742846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30977607262320817
  lightness: 0.25190891278907657
  saturation: 0.9747300997842103
  rhythmicContrast: 0.20213487790897489
purpose: []
